# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Assistant.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AssistantUI(object):
    def setupUi(self, AssistantUI):
        AssistantUI.setObjectName("AssistantUI")
        AssistantUI.resize(1109, 844)
        self.centralwidget = QtWidgets.QWidget(AssistantUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1121, 861))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../New folder/Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 220, 741, 451))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../New folder/Jarvis_Gui (1).gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, -40, 481, 171))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../New folder/initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(810, 760, 141, 61))
        self.pushButton.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"font: 18pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(950, 760, 141, 61))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"font: 18pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(800, 20, 291, 211))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../New folder/Code_Template.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(800, 240, 311, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../New folder/Hero_Template.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        AssistantUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(AssistantUI)
        QtCore.QMetaObject.connectSlotsByName(AssistantUI)

    def retranslateUi(self, AssistantUI):
        _translate = QtCore.QCoreApplication.translate
        AssistantUI.setWindowTitle(_translate("AssistantUI", "MainWindow"))
        self.pushButton.setText(_translate("AssistantUI", "START"))
        self.pushButton_2.setText(_translate("AssistantUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AssistantUI = QtWidgets.QMainWindow()
    ui = Ui_AssistantUI()
    ui.setupUi(AssistantUI)
    AssistantUI.show()
    sys.exit(app.exec_())
